//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RodOfGod.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComment
    {
        public int BlogCommentID { get; set; }
        public int BlogID { get; set; }
        public string Comment { get; set; }
        public string CommentOwner { get; set; }
        public int StatusTypeID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
